q for quick

diff --git a/bin/fzg b/bin/fzg
--- a/bin/fzg
+++ b/bin/fzg
@@ -623,7 +623,7 @@ makepoolwith() {
 if [ $# -eq 0 ]; then
     usage ; exiterror 1
 fi
-while getopts t:b:d:e:H:p:r:s:M:z:DcCiulxmfnvh o; do
+while getopts t:b:d:e:H:p:r:s:M:z:DcCiulxmfnqvh o; do
     case "$o" in
         t) TANKPART="$OPTARG" ;;
         b) ZFSBOOT_BOOT_POOL_SIZE="$OPTARG" ;;
@@ -645,6 +645,7 @@ while getopts t:b:d:e:H:p:r:s:M:z:DcCiulxmfnvh o; do
         m) FZG_MAKE_MFSROOT=1 ;;
         f) FZG_NEW_MFSROOT=1 ;;
         n) FZG_CHANGE_PASSWD=n ;;
+        q) FZG_QUICK=1 ;;
         v) echo $SCRIPTVERSION ; exiterror 1 ;;
         h) usage ; exiterror 1 ;;
         [?]) usage ; exiterror 1 ;;
@@ -1263,55 +1264,58 @@ append_motd $FZG_MNT
 
 
 if [ "$FZG_MAKE_MFSROOT" -o "$FZG_NEW_MFSROOT" ]; then
-    ### Actually make the MFSROOT
-    runorerror "dd if=/dev/zero of=${mfspath} bs=512 count=245760"
-    mdevice=`mdconfig -a -t vnode -f ${mfspath}`
-    mkdirorerror $FZG_MFS_MNT 755
-    runorerror "newfs /dev/${mdevice}"
-    runorerror "mount /dev/${mdevice} $FZG_MFS_MNT"
-    ### Copy everything except ...
-    tar -c -f - \
-        --exclude ./$ZFSBOOT_BOOT_POOL_NAME \
-        --exclude ./${FZG_RELEASE} \
-        --exclude ./etc/mail \
-        --exclude ./etc/pf \
-        --exclude ./etc/rc.conf.d \
-        --exclude ./etc/ssh \
-        --exclude ./usr \
-        --exclude ./var/at \
-        --exclude ./var/backups \
-        --exclude ./var/cache \
-        --exclude ./var/crash \
-        --exclude ./var/cron \
-        --exclude ./var/db \
-        --exclude ./var/log \
-        --exclude ./var/mail \
-        --exclude ./var/run \
-        --exclude ./var/spool \
-        --exclude ./var/tmp \
-        -C ${FZG_MNT} ./ | tar -C $FZG_MFS_MNT -x -f - || exiterror $? "tar -c -f - \
-        --exclude ./$ZFSBOOT_BOOT_POOL_NAME \
-        --exclude ./${FZG_RELEASE} \
-        --exclude ./etc/mail \
-        --exclude ./etc/pf \
-        --exclude ./etc/rc.conf.d \
-        --exclude ./etc/ssh \
-        --exclude ./usr \
-        --exclude ./var/at \
-        --exclude ./var/backups \
-        --exclude ./var/cache \
-        --exclude ./var/crash \
-        --exclude ./var/cron \
-        --exclude ./var/db \
-        --exclude ./var/log \
-        --exclude ./var/mail \
-        --exclude ./var/run \
-        --exclude ./var/spool \
-        --exclude ./var/tmp \
-        -C ${FZG_MNT} ./ _ tar -C $FZG_MFS_MNT -x -f -"
-    ### rc script for tmpfs /usr
-    ### modified from https://github.com/mmatuska/mfsbsd
-    cat >$FZG_MFS_MNT/etc/rc.d/mdinit <<EOF
+    if [ "$FZG_QUICK" ] && [ -e /boot/../mfsroot ]; then
+        install -m 644 /boot/../mfsroot ${mfspath}
+    else
+        ### Actually make the MFSROOT
+        runorerror "dd if=/dev/zero of=${mfspath} bs=512 count=245760"
+        mdevice=`mdconfig -a -t vnode -f ${mfspath}`
+        mkdirorerror $FZG_MFS_MNT 755
+        runorerror "newfs /dev/${mdevice}"
+        runorerror "mount /dev/${mdevice} $FZG_MFS_MNT"
+        ### Copy everything except ...
+        tar -c -f - \
+            --exclude ./$ZFSBOOT_BOOT_POOL_NAME \
+            --exclude ./${FZG_RELEASE} \
+            --exclude ./etc/mail \
+            --exclude ./etc/pf \
+            --exclude ./etc/rc.conf.d \
+            --exclude ./etc/ssh \
+            --exclude ./usr \
+            --exclude ./var/at \
+            --exclude ./var/backups \
+            --exclude ./var/cache \
+            --exclude ./var/crash \
+            --exclude ./var/cron \
+            --exclude ./var/db \
+            --exclude ./var/log \
+            --exclude ./var/mail \
+            --exclude ./var/run \
+            --exclude ./var/spool \
+            --exclude ./var/tmp \
+            -C ${FZG_MNT} ./ | tar -C $FZG_MFS_MNT -x -f - || exiterror $? "tar -c -f - \
+            --exclude ./$ZFSBOOT_BOOT_POOL_NAME \
+            --exclude ./${FZG_RELEASE} \
+            --exclude ./etc/mail \
+            --exclude ./etc/pf \
+            --exclude ./etc/rc.conf.d \
+            --exclude ./etc/ssh \
+            --exclude ./usr \
+            --exclude ./var/at \
+            --exclude ./var/backups \
+            --exclude ./var/cache \
+            --exclude ./var/crash \
+            --exclude ./var/cron \
+            --exclude ./var/db \
+            --exclude ./var/log \
+            --exclude ./var/mail \
+            --exclude ./var/run \
+            --exclude ./var/spool \
+            --exclude ./var/tmp \
+            -C ${FZG_MNT} ./ _ tar -C $FZG_MFS_MNT -x -f -"
+        ### rc script for tmpfs /usr
+        ### modified from https://github.com/mmatuska/mfsbsd
+        cat >$FZG_MFS_MNT/etc/rc.d/mdinit <<EOF
 #!/bin/sh
 # \$Id\$
 # PROVIDE: mdinit
@@ -1324,42 +1328,42 @@ start_cmd="mdinit_start"
 stop_cmd=":"
 mdinit_start()
 {
-  if [ -f /.usr.tar.xz ]; then
-    /rescue/test -d /usr || /rescue/mkdir /usr
-    /rescue/test -d /usr && /rescue/mount -t tmpfs tmpfs /usr
-    /rescue/test -d /usr && /rescue/tar -x -C / -f /.usr.tar.xz
-  elif [ -f /.usr.tar.bz2 ]; then
-    /rescue/test -d /usr || /rescue/mkdir /usr
-    /rescue/test -d /usr && /rescue/mount -t tmpfs tmpfs /usr
-    /rescue/test -d /usr && /rescue/tar -x -C / -f /.usr.tar.bz2
-  elif [ -f /.usr.tar.gz ]; then
-    /rescue/test -d /usr || /rescue/mkdir /usr
-    /rescue/test -d /usr && /rescue/mount -t tmpfs tmpfs /usr
-    /rescue/test -d /usr && /rescue/tar -x -C / -f /.usr.tar.gz
-  fi
-  if [ ! -f /usr/bin/which ]; then
-    echo "ERROR: in mdinit while extracting /usr, entering shell:"
-    /rescue/sh
-  fi
-  if zfs list -H -o name,canmount,mountpoint | awk '\$2 ~ /on/ {print}' | grep 'on[^/]*/\$' ; then
-    echo "Disabling some zfs datasets that mount to /"
-    DATASETS=\$(zfs list -H -o name,canmount,mountpoint | awk '\$2 ~ /on/ {print}' | grep 'on[^/]*/\$' | awk '{print \$1}')
-    for Z in \$DATASETS ; do
-      echo zfs set canmount=off \$Z
-      zfs set canmount=off \$Z
-    done
-  fi
-  if /bin/kenv -q mdinit_shell | grep YES ; then
-    echo "Found mdinit_shell, entering shell:"
-    /rescue/sh
-  fi
+    if [ -f /.usr.tar.xz ]; then
+        /rescue/test -d /usr || /rescue/mkdir /usr
+        /rescue/test -d /usr && /rescue/mount -t tmpfs tmpfs /usr
+        /rescue/test -d /usr && /rescue/tar -x -C / -f /.usr.tar.xz
+    elif [ -f /.usr.tar.bz2 ]; then
+        /rescue/test -d /usr || /rescue/mkdir /usr
+        /rescue/test -d /usr && /rescue/mount -t tmpfs tmpfs /usr
+        /rescue/test -d /usr && /rescue/tar -x -C / -f /.usr.tar.bz2
+    elif [ -f /.usr.tar.gz ]; then
+        /rescue/test -d /usr || /rescue/mkdir /usr
+        /rescue/test -d /usr && /rescue/mount -t tmpfs tmpfs /usr
+        /rescue/test -d /usr && /rescue/tar -x -C / -f /.usr.tar.gz
+    fi
+    if [ ! -f /usr/bin/which ]; then
+        echo "ERROR: in mdinit while extracting /usr, entering shell:"
+        /rescue/sh
+    fi
+    if zfs list -H -o name,canmount,mountpoint | awk '\$2 ~ /on/ {print}' | grep 'on[^/]*/\$' ; then
+        echo "Disabling some zfs datasets that mount to /"
+        DATASETS=\$(zfs list -H -o name,canmount,mountpoint | awk '\$2 ~ /on/ {print}' | grep 'on[^/]*/\$' | awk '{print \$1}')
+        for Z in \$DATASETS ; do
+            echo zfs set canmount=off \$Z
+            zfs set canmount=off \$Z
+        done
+    fi
+    if /bin/kenv -q mdinit_shell | grep YES ; then
+        echo "Found mdinit_shell, entering shell:"
+        /rescue/sh
+    fi
 }
 load_rc_config \$name
 run_rc_command "\$1"
 EOF
-    runorerror "chmod 555 $FZG_MFS_MNT/etc/rc.d/mdinit"
-    ### zpoolimport because we are in mfs and harder to persist
-    cat >$FZG_MFS_MNT/etc/rc.d/zpoolimport <<EOF
+        runorerror "chmod 555 $FZG_MFS_MNT/etc/rc.d/mdinit"
+        ### zpoolimport because we are in mfs and harder to persist
+        cat >$FZG_MFS_MNT/etc/rc.d/zpoolimport <<EOF
 #!/bin/sh
 # \$Id\$
 # PROVIDE: zpoolimport
@@ -1393,9 +1397,9 @@ zpoolimport_start()
 load_rc_config \$name
 run_rc_command "\$1"
 EOF
-    runorerror "chmod 555 $FZG_MFS_MNT/etc/rc.d/zpoolimport"
-    ### ucarp
-    cat >$FZG_MFS_MNT/etc/rc.d/wrapperucarp <<EOF
+        runorerror "chmod 555 $FZG_MFS_MNT/etc/rc.d/zpoolimport"
+        ### ucarp
+        cat >$FZG_MFS_MNT/etc/rc.d/wrapperucarp <<EOF
 #!/bin/sh
 # \$Id\$
 # PROVIDE: wrapperucarp
@@ -1414,9 +1418,9 @@ wrapperucarp_start()
 load_rc_config \$name
 run_rc_command "\$1"
 EOF
-    runorerror "chmod 555 $FZG_MFS_MNT/etc/rc.d/wrapperucarp"
-    ### packages because we are in mfs and harder to persist
-    cat >$FZG_MFS_MNT/etc/rc.d/packages <<EOF
+        runorerror "chmod 555 $FZG_MFS_MNT/etc/rc.d/wrapperucarp"
+        ### packages because we are in mfs and harder to persist
+        cat >$FZG_MFS_MNT/etc/rc.d/packages <<EOF
 #!/bin/sh
 # \$Id\$
 # PROVIDE: packages
@@ -1433,7 +1437,7 @@ do_p_install()
         ### force pkg to re-add to create user/groups
         pkg-static install -f -y \$P >/var/log/packages.net.log 2>&1
         echo "done"
-      done
+    done
     service ezjail start
     if ls /boot/packages/*.t?z >/dev/null 2>&1 ; then
         ### force pkg to re-add to create user/groups
@@ -1448,20 +1452,21 @@ packages_start()
 load_rc_config \$name
 run_rc_command "\$1"
 EOF
-    runorerror "chmod 555 $FZG_MFS_MNT/etc/rc.d/packages"
-    ### Package /usr
-    runorerror "tar -c -J -f $FZG_MFS_MNT/.usr.tar.xz --exclude ${FZG_RELEASE} --options xz:compression-level=9 -C ${FZG_MNT} usr"
-    ### if .cshrc
-    echo -n "Copying to ${FZG_MFS_MNT}/root/..."
-    for i in `ls /root/ | egrep '(.cshrc|.gitconfig|.tmux.conf)'` ; do
-        echo -n " ${i}"
-        runorerror "cp /root/${i} ${FZG_MFS_MNT}/root/"
-        runorerror     "chmod 600 ${FZG_MFS_MNT}/root/${i}"
-    done
-    echo " done"
-    ### Unmount
-    runorerror "umount /dev/${mdevice}"
-    runorerror "mdconfig -d -u ${mdevice#md}"
+        runorerror "chmod 555 $FZG_MFS_MNT/etc/rc.d/packages"
+        ### Package /usr
+        runorerror "tar -c -J -f $FZG_MFS_MNT/.usr.tar.xz --exclude ${FZG_RELEASE} --options xz:compression-level=9 -C ${FZG_MNT} usr"
+        ### if .cshrc
+        echo -n "Copying to ${FZG_MFS_MNT}/root/..."
+        for i in `ls /root/ | egrep '(.cshrc|.gitconfig|.tmux.conf)'` ; do
+            echo -n " ${i}"
+            runorerror "cp /root/${i} ${FZG_MFS_MNT}/root/"
+            runorerror     "chmod 600 ${FZG_MFS_MNT}/root/${i}"
+        done
+        echo " done"
+        ### Unmount
+        runorerror "umount /dev/${mdevice}"
+        runorerror "mdconfig -d -u ${mdevice#md}"
+    fi ### end of if [ "$FZG_QUICK" ] && [ -e /boot/../mfsroot ]; then
     freebsdconfiglocalmfsroot
 fi ### end of if [ "$FZG_MAKE_MFSROOT" -o "$FZG_NEW_MFSROOT" ]; then
 
