sync instead of sleep, also fix GPARTS

diff --git a/bin/fzg b/bin/fzg
--- a/bin/fzg
+++ b/bin/fzg
@@ -3,7 +3,7 @@
 ######################################################################
 # Script version is YYmmdd-HHMM in UTC, date +%y%m%d-%H%M%S
 ######################################################################
-SCRIPTVERSION=141124-085017
+SCRIPTVERSION=141124-093023
 
 ######################################################################
 # Variables you can edit / pass
@@ -34,7 +34,7 @@ RESTOREMASK=`umask`
 
 usage() {
   cat <<EOF
-usage:  $0 -d disk [-d disk ...] [-e disk]
+usage:  ${0##*/} -d disk [-d disk ...] [-e disk]
         [-b boot_size] [-f] [-h] [-m] [-M /mnt] [-p poolname]
         [-r stripe|mirror|raidz|raidz2|raidz3] [-s swap_size] [-v]
         [-z pool_size]
@@ -52,35 +52,42 @@ usage:  $0 -d disk [-d disk ...] [-e disk]
         -v       Version.
         -z size  ZFS pool size.
 
-        $0 -i -d vdev [-d vdev ...] [-p poolname]
-        $0 -i -e vdev -d vdev [-p poolname]
-        $0 -u -d vdev [-d vdev ...] [-p poolname]
-        $0 -l [-p poolname]
+        ${0##*/} -i -d vdev [-d vdev ...] [-p poolname] [-x]
+        ${0##*/} -i -e vdev -d vdev [-p poolname]
+        ${0##*/} -u -d vdev [-d vdev ...] [-p poolname]
+        ${0##*/} -l [-p poolname]
 
         -i       Initialize data partition with geli and create pool.
         -l       Export pool and lock data partition.
         -u       Unlock data partition and mount pool.
+        -x       Automatically create partition 5.
         -d vdev  Virtual device to grab gptid label from (eg. da0p5)
 
 examples:
 
   Install on disk 0, pool name mini with size 2 GB:
-        $0 -d ada0 -z 2g -p mini
+        ${0##*/} -d ada0 -z 2g -p mini
 
   Add disk 1 as mirror to existing pool mini that contains disk ada0:
-        $0 -e ada0 -z 2g -p mini -d ada1
+        ${0##*/} -e ada0 -d ada1 -z 2g -p mini
+
+  Add data partition:
+        ${0##*/} -i -d ada0 -p tank -x
+
+  Attach another disk to data partition:
+        ${0##*/} -i -e ada0 -d ada1 -p tank
 
 other examples:
 
   Install on 3 mirror disks, a boot pool 1 GB, swap 1 GB, ZFS root pool 2 GB:
-        $0 -d ada0 -d ada1 -d ada2 -b 1g -s 1g -z 2g -r mirror
+        ${0##*/} -d ada0 -d ada1 -d ada2 -b 1g -s 1g -z 2g -r mirror
 
   Make a bootable ZFS USB, which loads as mfs:
   Note we change the pool name so they don't conflict.
-        $0 -d da0 -m -p usb
+        ${0##*/} -d da0 -m -p usb
 
   Minimal mirror mfs server:
-        $0 -d ada0 -d ada1 -z 2g -f -m -p mini
+        ${0##*/} -d ada0 -d ada1 -z 2g -f -m -p mini
 EOF
 }
 
@@ -185,7 +192,7 @@ makepoolwith() {
         echo " error at create"
         exit 1
       fi
-      sleep 1
+      sync
       if ! echo "a 1" | fdisk -f - "$DEV" >/dev/null 2>&1 ; then
         echo " error at fdisk"
         exit 1
@@ -255,7 +262,6 @@ makepoolwith() {
       fi
       echo " done"
     done
-    sleep 1
     ########## create main root pool
     [ "$raidtype" != "stripe" ] && TRAID=$raidtype
     echo -n "Creating ZFS pool $rpool on $TPARTS ..."
@@ -357,6 +363,10 @@ makepoolwith() {
 # Options parsing
 # modified from https://github.com/mmatuska/mfsbsd
 ######################################################################
+
+if [ $# -eq 0 ]; then
+  usage; exit 1
+fi
 
 while getopts b:d:e:p:r:s:M:z:iulxmfvh o; do
   case "$o" in
@@ -510,13 +520,14 @@ if [ "$DATAINIT" ]; then
           if [ "$PARTCREATED" != "1" ]; then
             if /sbin/gpart add -i 5 -t freebsd-zfs $align4k -s ${GSIZE}G \
               ${disk} >/dev/null 2>&1 ; then
-              echo " success adding partition sized ${GSIZE}G at $DEV"
+              echo " success adding partition sized ${GSIZE}G at $disk"
               PARTCREATED=1
               gptidtarget=`glabel list ${disk}p5 | grep Name | head -1 | \
                 awk '{print $NF}'`
               dd if=/dev/zero of="/dev/$gptidtarget" bs=512 count=560 \
                 >/dev/null 2>&1
               zpool labelclear -f "/dev/$gptidtarget" >/dev/null 2>&1
+              GPARTS="$GPARTS ${disk}p5"
             else
               ########## we should actually use the next datasizes,
               ########## but for now we'll decrement by 1
@@ -525,12 +536,13 @@ if [ "$DATAINIT" ]; then
           fi
           if [ $GSIZE -lt 1 ]; then
             PARTCREATED=2
-            echo " error adding partition at $DEV"
+            echo " error adding partition at $disk"
           fi
         done
       done
       [ "$PARTCREATED" != "1" ] && exit 1
     done
+    disks="$GPARTS"
   fi
   if [ ! -e ${datakey} ]; then
     stty -echo
@@ -587,7 +599,7 @@ elif [ "$DATALOCK" ]; then
     exit 1
   fi
   echo " done"
-  sleep 2
+  sync
   echo -n "Detaching disks ..."
   for disk in $disks; do
     echo " $disk"
