rename keypkg to keygeli

diff --git a/etc/rc.d/keygeli b/etc/rc.d/keygeli
--- a/etc/rc.d/keygeli
+++ b/etc/rc.d/keygeli
@@ -1,35 +1,35 @@
 #!/bin/sh
 
 # $FreeBSD$
-# PROVIDE: keypkg
+# PROVIDE: keygeli
 # REQUIRE: FILESYSTEMS NETWORKING SERVERS DAEMON LOGIN
 # BEFORE: sshd iocage
 
 # Add the following lines to /etc/rc.conf.local or /etc/rc.conf to enable this:
 #
-# keypkg_enable="YES"
+# keygeli_enable="YES"
 #
 # If you use a USB key with ZFS, the zpool name can be set with
 #
-# keypkg_zpool="key"
+# keygeli_zpool="key"
 #
 # If you use ssh keyservers:
 #
-# keypkg_ssh="one two three"
-# keypkg_ssh_flags="-F $keypkg_ssh_config -o UserKnownHostsFile=/etc/keypkg/known_hosts -i /etc/keypkg/id_rsa"
+# keygeli_ssh="one two three"
+# keygeli_ssh_flags="-F $keygeli_ssh_config -o UserKnownHostsFile=/etc/keygeli/known_hosts -i /etc/keygeli/id_rsa"
 
 . /etc/rc.subr
 
-: ${keypkg_enable:="NO"}
-: ${keypkg_export:="YES"}
-: ${keypkg_tmpfsdir:="/tmp/tmpfs"}
-: ${keypkg_file:=keypkg_$(hostname -s).smime}
-: ${keypkg_key:="/etc/keypkg/key.pem"}
-: ${keypkg_cert:="/etc/keypkg/cert.pem"}
+: ${keygeli_enable:="NO"}
+: ${keygeli_export:="YES"}
+: ${keygeli_tmpfsdir:="/tmp/tmpfs"}
+: ${keygeli_file:=keygeli_$(hostname -s).smime}
+: ${keygeli_key:="/etc/keygeli/key.pem"}
+: ${keygeli_cert:="/etc/keygeli/cert.pem"}
 
-name="keypkg"
-rcvar=keypkg_enable
-start_cmd="keypkg_run"
+name="keygeli"
+rcvar=keygeli_enable
+start_cmd="keygeli_run"
 stop_cmd=":"
 exfile=/etc/exports
 
@@ -62,42 +62,42 @@ ipexports()
     fi
 }
 
-keypkg_run()
+keygeli_run()
 {
 
     # restrictive mask for new files
     umask 077
 
     # mount tmpfs to keep the passfile in ram
-    mkdir -p $keypkg_tmpfsdir
-    chmod 700 $keypkg_tmpfsdir
-    mount -t tmpfs tmpfs $keypkg_tmpfsdir
+    mkdir -p $keygeli_tmpfsdir
+    chmod 700 $keygeli_tmpfsdir
+    mount -t tmpfs tmpfs $keygeli_tmpfsdir
     if ! mount | grep 'tmpfs on /tmp/tmpfs (tmpfs' >/dev/null 2>&1 ; then
         exit 1
     fi
 
-    # Fetch keypkg_hostname.smime from usb key zpool or ssh
-    if [ -n "$keypkg_zpool" ]; then
-        if ! zpool list ${keypkg_zpool} >/dev/null 2>&1 ; then
+    # Fetch keygeli_hostname.smime from usb key zpool or ssh
+    if [ -n "$keygeli_zpool" ]; then
+        if ! zpool list ${keygeli_zpool} >/dev/null 2>&1 ; then
             # if not already exist, import the pool on the USB thumbdrive
-            zpool import ${keypkg_zpool_import_flags} ${keypkg_zpool}
+            zpool import ${keygeli_zpool_import_flags} ${keygeli_zpool}
         fi
-        if zfs list -H -o mountpoint $keypkg_zpool >/dev/null 2>&1 ; then
-            keypkg_zpool_mountpoint=$( zfs list -H -o mountpoint $keypkg_zpool )
-            if [ -e ${keypkg_zpool_mountpoint}/${keypkg_file} ]; then
+        if zfs list -H -o mountpoint $keygeli_zpool >/dev/null 2>&1 ; then
+            keygeli_zpool_mountpoint=$( zfs list -H -o mountpoint $keygeli_zpool )
+            if [ -e ${keygeli_zpool_mountpoint}/${keygeli_file} ]; then
                 # copy to standard location in tmpfs
-                cat ${keypkg_zpool_mountpoint}/${keypkg_file} > ${keypkg_tmpfsdir}/${keypkg_file}
+                cat ${keygeli_zpool_mountpoint}/${keygeli_file} > ${keygeli_tmpfsdir}/${keygeli_file}
             fi
         fi
     fi
-    if [ -n "$keypkg_ssh" ]; then
-        for i in $keypkg_ssh ; do
-            if [ ! -e ${keypkg_tmpfsdir}/${keypkg_file} ]; then
+    if [ -n "$keygeli_ssh" ]; then
+        for i in $keygeli_ssh ; do
+            if [ ! -e ${keygeli_tmpfsdir}/${keygeli_file} ]; then
                 # copy to standard location in tmpfs
-                if ! ssh $keypkg_ssh_flags $i keypkg get > ${keypkg_tmpfsdir}/${keypkg_file} ; then
-                    if [ -e ${keypkg_tmpfsdir}/${keypkg_file} ]; then
+                if ! ssh $keygeli_ssh_flags $i keygeli get > ${keygeli_tmpfsdir}/${keygeli_file} ; then
+                    if [ -e ${keygeli_tmpfsdir}/${keygeli_file} ]; then
                         # exit code != 0, so this shouldn't exist
-                        rm ${keypkg_tmpfsdir}/${keypkg_file}
+                        rm ${keygeli_tmpfsdir}/${keygeli_file}
                     fi
                     sleep 5
                 fi
@@ -106,19 +106,19 @@ keypkg_run()
     fi
 
     # Verify, then Decrypt then verify
-    if [ -e ${keypkg_tmpfsdir}/${keypkg_file} ]; then
+    if [ -e ${keygeli_tmpfsdir}/${keygeli_file} ]; then
         # Verify package was for self
-        if ! openssl smime -verify -CAfile $keypkg_cert -certfile $keypkg_cert \
-                -in ${keypkg_tmpfsdir}/${keypkg_file} >/dev/null 2>/dev/null ; then
-            echo "Verification of ${keypkg_tmpfsdir}/${keypkg_file} failed."
+        if ! openssl smime -verify -CAfile $keygeli_cert -certfile $keygeli_cert \
+                -in ${keygeli_tmpfsdir}/${keygeli_file} >/dev/null 2>/dev/null ; then
+            echo "Verification of ${keygeli_tmpfsdir}/${keygeli_file} failed."
             exit 1
         fi
-        openssl smime -verify -CAfile $keypkg_cert -certfile $keypkg_cert \
-            -in ${keypkg_tmpfsdir}/${keypkg_file} 2>/dev/null \
-                | openssl smime -decrypt -binary -nointern -recip $keypkg_cert -inkey $keypkg_key \
-                | openssl smime -verify -CAfile $keypkg_cert -certfile $keypkg_cert \
-                    -out ${keypkg_tmpfsdir}/geli_password.txt 2>/dev/null
-        chmod 600 ${keypkg_tmpfsdir}/geli_password.txt
+        openssl smime -verify -CAfile $keygeli_cert -certfile $keygeli_cert \
+            -in ${keygeli_tmpfsdir}/${keygeli_file} 2>/dev/null \
+                | openssl smime -decrypt -binary -nointern -recip $keygeli_cert -inkey $keygeli_key \
+                | openssl smime -verify -CAfile $keygeli_cert -certfile $keygeli_cert \
+                    -out ${keygeli_tmpfsdir}/geli_password.txt 2>/dev/null
+        chmod 600 ${keygeli_tmpfsdir}/geli_password.txt
     fi
 
     # geli flags should be configured in rc.conf
@@ -126,12 +126,12 @@ keypkg_run()
     service geli2 start
 
     # unmount tmpfs so we get rid of the memory
-    umount -f $keypkg_tmpfsdir
+    umount -f $keygeli_tmpfsdir
 
-    if [ -n "$keypkg_zpool" ]; then
-        if checkyesno keypkg_export && zpool list ${keypkg_zpool} >/dev/null 2>&1 ; then
+    if [ -n "$keygeli_zpool" ]; then
+        if checkyesno keygeli_export && zpool list ${keygeli_zpool} >/dev/null 2>&1 ; then
             # export the pool on the USB thumbdrive
-            zpool export ${keypkg_zpool}
+            zpool export ${keygeli_zpool}
         fi
     fi
 
